In [66]:
import torch

In [67]:
x = torch.randn(3, requires_grad=True)
print(x)

tensor([-0.4287,  1.0263,  1.4064], requires_grad=True)


In [68]:
y = x + 2
print(y)

tensor([1.5713, 3.0263, 3.4064], grad_fn=<AddBackward0>)


In [69]:
z = y*y*2
z = z.mean()
print(z)

tensor(15.4873, grad_fn=<MeanBackward0>)


In [70]:
z.backward()  # dz/dx
print(x.grad)

tensor([2.0951, 4.0351, 4.5418])


In [71]:
weights = torch.ones(4, requires_grad=True)

In [72]:
for epoch in range(3):
    model_output = (weights * 3).sum()  # Forward (y = w * 3)

    model_output.backward()             # Backward (dy/dw = 3): Calcula a variação e ajusta os pesos

    print(weights.grad)                 # Exibe os pesos ajustados

    # weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])
