In [1]:
import torch
import numpy as np

In [2]:
torch.empty(1)

tensor([0.])

In [3]:
torch.empty(3)

tensor([0., 0., 0.])

In [4]:
torch.empty(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
torch.empty(2,2,3)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [6]:
torch.rand(2,2)

tensor([[0.1538, 0.0253],
        [0.5604, 0.3850]])

In [7]:
x = torch.ones(2,2, dtype=torch.float16)
print(x)
print(x.size())

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float16)
torch.Size([2, 2])


In [8]:
x = torch.tensor([2.5, 0.1])
print(x)

tensor([2.5000, 0.1000])


In [9]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

z = x + y
z = torch.add(x,y)
print(z)

tensor([[0.7314, 0.4736],
        [0.5358, 0.7400]])
tensor([[0.6371, 0.2746],
        [0.7283, 0.3884]])
tensor([[1.3685, 0.7482],
        [1.2641, 1.1284]])


In [10]:
x = torch.rand(2,2)
y = torch.rand(2,2)
y.add_(x)
print(y)

tensor([[1.5323, 0.9094],
        [1.7852, 0.7255]])


In [11]:
z = x - y
z = torch.sub(x, y)
print(z)

tensor([[-0.9944, -0.1778],
        [-0.9008, -0.2098]])


In [12]:
z = x * y
z = torch.mul(x, y)
print(z)

tensor([[0.8242, 0.6653],
        [1.5789, 0.3742]])


In [13]:
z = x / y
z = torch.div(x, y)
print(z)

tensor([[0.3510, 0.8045],
        [0.4954, 0.7109]])


In [14]:
x = torch.rand(5, 3)
print(x)
print(x[1, 1].item())

tensor([[0.4016, 0.3203, 0.0300],
        [0.1690, 0.9043, 0.5239],
        [0.0934, 0.4467, 0.5375],
        [0.3317, 0.7020, 0.6010],
        [0.7183, 0.1400, 0.5568]])
0.904267430305481


In [15]:
x = torch.rand(4, 3)
print(x)
print(x.view(12))

tensor([[0.8997, 0.2126, 0.8487],
        [0.3559, 0.4627, 0.9512],
        [0.8239, 0.0505, 0.4423],
        [0.0886, 0.2408, 0.4641]])
tensor([0.8997, 0.2126, 0.8487, 0.3559, 0.4627, 0.9512, 0.8239, 0.0505, 0.4423,
        0.0886, 0.2408, 0.4641])


In [19]:
a = torch.rand(5)
b = a.numpy()
print(a)
print(b)

tensor([0.1987, 0.7618, 0.3278, 0.1212, 0.4377])
[0.19869447 0.7617949  0.32777017 0.12117481 0.43774468]


In [22]:
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

a += 1
print(a)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]


In [ ]:
# gpu
if torch.cuda.is_available():         # se gpu está disponível
    device = torch.device("cuda")     # salva o serviço: gpu
    x = torch.ones(5, device=device)  # define o serviço onde será carregado e rodará: gpu
    y = torch.ones(5)
    y = y.to(device)                  # define o serviço onde será carregado e rodará: gpu
    z = x + y
    z = z.to("cpu")                   # define o serviço onde será carregado e rodará: cpu

In [25]:
x = torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
